// schemas/fullLeadSchema.ts
import { z } from 'zod';

export const fullLeadSchema = z.object({
  attributes: z.object({
    type: z.literal("Lead"),
    url: z.string(),
  }),
  Id: z.string(),
  IsDeleted: z.boolean(),
  MasterRecordId: z.string().nullable(),
  LastName: z.string(),
  FirstName: z.string(),
  Salutation: z.string().nullable(),
  Name: z.string(),
  Title: z.string().nullable(),
  Company: z.string(),
  Street: z.string().nullable(),
  City: z.string().nullable(),
  State: z.string().nullable(),
  PostalCode: z.string().nullable(),
  Country: z.string().nullable(),
  Latitude: z.number().nullable(),
  Longitude: z.number().nullable(),
  GeocodeAccuracy: z.string().nullable(),
  Address: z.any().nullable(), // Address object sometimes or null
  Phone: z.string().nullable(),
  MobilePhone: z.string().nullable(),
  Fax: z.string().nullable(),
  Email: z.string().nullable(),
  Website: z.string().nullable(),
  PhotoUrl: z.string(),
  Description: z.string().nullable(),
  LeadSource: z.string().nullable(),
  Status: z.string(), // could also be enum if fixed
  Industry: z.string().nullable(),
  Rating: z.string().nullable(),
  AnnualRevenue: z.number().nullable(),
  NumberOfEmployees: z.number().nullable(),
  OwnerId: z.string(),
  IsConverted: z.boolean(),
  ConvertedDate: z.string().nullable(),
  ConvertedAccountId: z.string().nullable(),
  ConvertedContactId: z.string().nullable(),
  ConvertedOpportunityId: z.string().nullable(),
  IsUnreadByOwner: z.boolean(),
  CreatedDate: z.string(), // ISO datetime string
  CreatedById: z.string(),
  LastModifiedDate: z.string(),
  LastModifiedById: z.string(),
  SystemModstamp: z.string(),
  LastActivityDate: z.string().nullable(),
  LastViewedDate: z.string(),
  LastReferencedDate: z.string(),
  Jigsaw: z.string().nullable(),
  JigsawContactId: z.string().nullable(),
  CleanStatus: z.string().nullable(),
  CompanyDunsNumber: z.string().nullable(),
  DandbCompanyId: z.string().nullable(),
  EmailBouncedReason: z.string().nullable(),
  EmailBouncedDate: z.string().nullable(),
  SICCode__c: z.string().nullable(),
  ProductInterest__c: z.string().nullable(),
  Primary__c: z.string().nullable(),
  CurrentGenerators__c: z.string().nullable(),
  NumberofLocations__c: z.number().nullable()
});
